// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ofgp/ofgp-core/business/p2p/p2p.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "github.com/ofgp/ofgp-core/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type P2PMsg struct {
	SendAddr             string   `protobuf:"bytes,2,opt,name=send_addr,json=sendAddr,proto3" json:"send_addr,omitempty"`
	ReceiveAddr          string   `protobuf:"bytes,3,opt,name=receive_addr,json=receiveAddr,proto3" json:"receive_addr,omitempty"`
	Chain                uint32   `protobuf:"varint,4,opt,name=chain,proto3" json:"chain,omitempty"`
	TokenId              uint32   `protobuf:"varint,5,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Amount               uint64   `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee                  uint64   `protobuf:"varint,7,opt,name=fee,proto3" json:"fee,omitempty"`
	ExpiredTime          uint32   `protobuf:"varint,8,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time,omitempty"`
	RequireAddr          string   `protobuf:"bytes,9,opt,name=require_addr,json=requireAddr,proto3" json:"require_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PMsg) Reset()         { *m = P2PMsg{} }
func (m *P2PMsg) String() string { return proto.CompactTextString(m) }
func (*P2PMsg) ProtoMessage()    {}
func (*P2PMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_2c0da47d0d807168, []int{0}
}
func (m *P2PMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PMsg.Unmarshal(m, b)
}
func (m *P2PMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PMsg.Marshal(b, m, deterministic)
}
func (dst *P2PMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PMsg.Merge(dst, src)
}
func (m *P2PMsg) XXX_Size() int {
	return xxx_messageInfo_P2PMsg.Size(m)
}
func (m *P2PMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PMsg.DiscardUnknown(m)
}

var xxx_messageInfo_P2PMsg proto.InternalMessageInfo

func (m *P2PMsg) GetSendAddr() string {
	if m != nil {
		return m.SendAddr
	}
	return ""
}

func (m *P2PMsg) GetReceiveAddr() string {
	if m != nil {
		return m.ReceiveAddr
	}
	return ""
}

func (m *P2PMsg) GetChain() uint32 {
	if m != nil {
		return m.Chain
	}
	return 0
}

func (m *P2PMsg) GetTokenId() uint32 {
	if m != nil {
		return m.TokenId
	}
	return 0
}

func (m *P2PMsg) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *P2PMsg) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *P2PMsg) GetExpiredTime() uint32 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *P2PMsg) GetRequireAddr() string {
	if m != nil {
		return m.RequireAddr
	}
	return ""
}

// 待匹配交易
type P2PInfo struct {
	Event                *proto1.WatchedEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Msg                  *P2PMsg              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Time                 int64                `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *P2PInfo) Reset()         { *m = P2PInfo{} }
func (m *P2PInfo) String() string { return proto.CompactTextString(m) }
func (*P2PInfo) ProtoMessage()    {}
func (*P2PInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_2c0da47d0d807168, []int{1}
}
func (m *P2PInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PInfo.Unmarshal(m, b)
}
func (m *P2PInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PInfo.Marshal(b, m, deterministic)
}
func (dst *P2PInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PInfo.Merge(dst, src)
}
func (m *P2PInfo) XXX_Size() int {
	return xxx_messageInfo_P2PInfo.Size(m)
}
func (m *P2PInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PInfo.DiscardUnknown(m)
}

var xxx_messageInfo_P2PInfo proto.InternalMessageInfo

func (m *P2PInfo) GetEvent() *proto1.WatchedEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *P2PInfo) GetMsg() *P2PMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *P2PInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

type P2PConfirmMsg struct {
	Opration             uint32   `protobuf:"varint,1,opt,name=opration,proto3" json:"opration,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TxId                 string   `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Chain                uint32   `protobuf:"varint,4,opt,name=chain,proto3" json:"chain,omitempty"`
	Height               uint64   `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash            string   `protobuf:"bytes,6,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Amount               uint64   `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee                  uint64   `protobuf:"varint,8,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PConfirmMsg) Reset()         { *m = P2PConfirmMsg{} }
func (m *P2PConfirmMsg) String() string { return proto.CompactTextString(m) }
func (*P2PConfirmMsg) ProtoMessage()    {}
func (*P2PConfirmMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_2c0da47d0d807168, []int{2}
}
func (m *P2PConfirmMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PConfirmMsg.Unmarshal(m, b)
}
func (m *P2PConfirmMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PConfirmMsg.Marshal(b, m, deterministic)
}
func (dst *P2PConfirmMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PConfirmMsg.Merge(dst, src)
}
func (m *P2PConfirmMsg) XXX_Size() int {
	return xxx_messageInfo_P2PConfirmMsg.Size(m)
}
func (m *P2PConfirmMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PConfirmMsg.DiscardUnknown(m)
}

var xxx_messageInfo_P2PConfirmMsg proto.InternalMessageInfo

func (m *P2PConfirmMsg) GetOpration() uint32 {
	if m != nil {
		return m.Opration
	}
	return 0
}

func (m *P2PConfirmMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *P2PConfirmMsg) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *P2PConfirmMsg) GetChain() uint32 {
	if m != nil {
		return m.Chain
	}
	return 0
}

func (m *P2PConfirmMsg) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *P2PConfirmMsg) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *P2PConfirmMsg) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *P2PConfirmMsg) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type WaitConfirmMsg struct {
	Opration             uint32          `protobuf:"varint,1,opt,name=opration,proto3" json:"opration,omitempty"`
	Chain                uint32          `protobuf:"varint,2,opt,name=chain,proto3" json:"chain,omitempty"`
	Info                 *P2PConfirmInfo `protobuf:"bytes,3,opt,name=info,proto3" json:"info,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WaitConfirmMsg) Reset()         { *m = WaitConfirmMsg{} }
func (m *WaitConfirmMsg) String() string { return proto.CompactTextString(m) }
func (*WaitConfirmMsg) ProtoMessage()    {}
func (*WaitConfirmMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_2c0da47d0d807168, []int{3}
}
func (m *WaitConfirmMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitConfirmMsg.Unmarshal(m, b)
}
func (m *WaitConfirmMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitConfirmMsg.Marshal(b, m, deterministic)
}
func (dst *WaitConfirmMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitConfirmMsg.Merge(dst, src)
}
func (m *WaitConfirmMsg) XXX_Size() int {
	return xxx_messageInfo_WaitConfirmMsg.Size(m)
}
func (m *WaitConfirmMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitConfirmMsg.DiscardUnknown(m)
}

var xxx_messageInfo_WaitConfirmMsg proto.InternalMessageInfo

func (m *WaitConfirmMsg) GetOpration() uint32 {
	if m != nil {
		return m.Opration
	}
	return 0
}

func (m *WaitConfirmMsg) GetChain() uint32 {
	if m != nil {
		return m.Chain
	}
	return 0
}

func (m *WaitConfirmMsg) GetInfo() *P2PConfirmInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

// 被确认交易
type P2PConfirmInfo struct {
	Event                *proto1.WatchedEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Msg                  *P2PConfirmMsg       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *P2PConfirmInfo) Reset()         { *m = P2PConfirmInfo{} }
func (m *P2PConfirmInfo) String() string { return proto.CompactTextString(m) }
func (*P2PConfirmInfo) ProtoMessage()    {}
func (*P2PConfirmInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_2c0da47d0d807168, []int{4}
}
func (m *P2PConfirmInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PConfirmInfo.Unmarshal(m, b)
}
func (m *P2PConfirmInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PConfirmInfo.Marshal(b, m, deterministic)
}
func (dst *P2PConfirmInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PConfirmInfo.Merge(dst, src)
}
func (m *P2PConfirmInfo) XXX_Size() int {
	return xxx_messageInfo_P2PConfirmInfo.Size(m)
}
func (m *P2PConfirmInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PConfirmInfo.DiscardUnknown(m)
}

var xxx_messageInfo_P2PConfirmInfo proto.InternalMessageInfo

func (m *P2PConfirmInfo) GetEvent() *proto1.WatchedEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *P2PConfirmInfo) GetMsg() *P2PConfirmMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SendedTx struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Time                 int64    `protobuf:"varint,2,opt,name=time,proto3" json:"time,omitempty"`
	SignTerm             int64    `protobuf:"varint,3,opt,name=sign_term,json=signTerm,proto3" json:"sign_term,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendedTx) Reset()         { *m = SendedTx{} }
func (m *SendedTx) String() string { return proto.CompactTextString(m) }
func (*SendedTx) ProtoMessage()    {}
func (*SendedTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_2c0da47d0d807168, []int{5}
}
func (m *SendedTx) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendedTx.Unmarshal(m, b)
}
func (m *SendedTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendedTx.Marshal(b, m, deterministic)
}
func (dst *SendedTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendedTx.Merge(dst, src)
}
func (m *SendedTx) XXX_Size() int {
	return xxx_messageInfo_SendedTx.Size(m)
}
func (m *SendedTx) XXX_DiscardUnknown() {
	xxx_messageInfo_SendedTx.DiscardUnknown(m)
}

var xxx_messageInfo_SendedTx proto.InternalMessageInfo

func (m *SendedTx) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *SendedTx) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *SendedTx) GetSignTerm() int64 {
	if m != nil {
		return m.SignTerm
	}
	return 0
}

// 创建待匹配交易索引
type TxNode struct {
	Value                string             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Childs               map[string]*TxNode `protobuf:"bytes,2,rep,name=childs,proto3" json:"childs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TxNode) Reset()         { *m = TxNode{} }
func (m *TxNode) String() string { return proto.CompactTextString(m) }
func (*TxNode) ProtoMessage()    {}
func (*TxNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_2c0da47d0d807168, []int{6}
}
func (m *TxNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxNode.Unmarshal(m, b)
}
func (m *TxNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxNode.Marshal(b, m, deterministic)
}
func (dst *TxNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxNode.Merge(dst, src)
}
func (m *TxNode) XXX_Size() int {
	return xxx_messageInfo_TxNode.Size(m)
}
func (m *TxNode) XXX_DiscardUnknown() {
	xxx_messageInfo_TxNode.DiscardUnknown(m)
}

var xxx_messageInfo_TxNode proto.InternalMessageInfo

func (m *TxNode) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TxNode) GetChilds() map[string]*TxNode {
	if m != nil {
		return m.Childs
	}
	return nil
}

func init() {
	proto.RegisterType((*P2PMsg)(nil), "p2p.p2pMsg")
	proto.RegisterType((*P2PInfo)(nil), "p2p.p2pInfo")
	proto.RegisterType((*P2PConfirmMsg)(nil), "p2p.p2pConfirmMsg")
	proto.RegisterType((*WaitConfirmMsg)(nil), "p2p.waitConfirmMsg")
	proto.RegisterType((*P2PConfirmInfo)(nil), "p2p.p2pConfirmInfo")
	proto.RegisterType((*SendedTx)(nil), "p2p.sendedTx")
	proto.RegisterType((*TxNode)(nil), "p2p.txNode")
	proto.RegisterMapType((map[string]*TxNode)(nil), "p2p.txNode.ChildsEntry")
}

func init() {
	proto.RegisterFile("github.com/ofgp/ofgp-core/business/p2p/p2p.proto", fileDescriptor_p2p_2c0da47d0d807168)
}

var fileDescriptor_p2p_2c0da47d0d807168 = []byte{
	// 573 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0xd1, 0x6e, 0xd3, 0x3c,
	0x14, 0xc7, 0x95, 0xb4, 0x4d, 0xd3, 0x93, 0x6f, 0xd3, 0x27, 0x0f, 0x8d, 0x30, 0x34, 0xa9, 0x8b,
	0x90, 0x28, 0x42, 0xb4, 0x28, 0xdc, 0x20, 0xee, 0xd0, 0x34, 0xc4, 0x2e, 0x40, 0x28, 0x9a, 0xc4,
	0x65, 0x95, 0xc6, 0x4e, 0x62, 0x75, 0xb1, 0x8d, 0xe3, 0x8e, 0xee, 0x49, 0x78, 0x24, 0x9e, 0x85,
	0xb7, 0x40, 0x3e, 0x71, 0xbb, 0x80, 0x98, 0x04, 0x17, 0x9b, 0x7c, 0xfe, 0xe7, 0xf8, 0x9c, 0xe3,
	0xdf, 0x3f, 0x85, 0x97, 0x15, 0x37, 0xf5, 0x66, 0x35, 0x2f, 0x64, 0xb3, 0x90, 0x65, 0xa5, 0xf0,
	0xdf, 0x8b, 0x42, 0x6a, 0xb6, 0x58, 0x6d, 0x5a, 0x2e, 0x58, 0xdb, 0x2e, 0x54, 0xaa, 0xec, 0xdf,
	0x5c, 0x69, 0x69, 0x24, 0x19, 0xa8, 0x54, 0x9d, 0x3c, 0xbf, 0xff, 0x1a, 0x56, 0x2d, 0x56, 0x3a,
	0x2f, 0x4d, 0x77, 0x23, 0xf9, 0xe1, 0x41, 0xa0, 0x52, 0xf5, 0xa1, 0xad, 0xc8, 0x63, 0x98, 0xb4,
	0x4c, 0xd0, 0x65, 0x4e, 0xa9, 0x8e, 0xfd, 0xa9, 0x37, 0x9b, 0x64, 0xa1, 0x15, 0xde, 0x52, 0xaa,
	0xc9, 0x19, 0xfc, 0xa7, 0x59, 0xc1, 0xf8, 0x0d, 0xeb, 0xf2, 0x03, 0xcc, 0x47, 0x4e, 0xc3, 0x92,
	0x07, 0x30, 0x2a, 0xea, 0x9c, 0x8b, 0x78, 0x38, 0xf5, 0x66, 0x07, 0x59, 0x17, 0x90, 0x47, 0x10,
	0x1a, 0xb9, 0x66, 0x62, 0xc9, 0x69, 0x3c, 0xc2, 0xc4, 0x18, 0xe3, 0x4b, 0x4a, 0x8e, 0x21, 0xc8,
	0x1b, 0xb9, 0x11, 0x26, 0x0e, 0xa6, 0xde, 0x6c, 0x98, 0xb9, 0x88, 0xfc, 0x0f, 0x83, 0x92, 0xb1,
	0x78, 0x8c, 0xa2, 0x3d, 0xda, 0xe9, 0x6c, 0xab, 0xb8, 0x66, 0x74, 0x69, 0x78, 0xc3, 0xe2, 0x10,
	0x1b, 0x45, 0x4e, 0xbb, 0xe2, 0x0d, 0xeb, 0x16, 0xfc, 0xb2, 0xe1, 0xda, 0x2d, 0x38, 0xd9, 0x2d,
	0x88, 0x9a, 0x5d, 0x30, 0xa9, 0x60, 0xac, 0x52, 0x75, 0x29, 0x4a, 0x49, 0x9e, 0xc1, 0x88, 0xdd,
	0x30, 0x61, 0x62, 0x6f, 0xea, 0xcd, 0xa2, 0xf4, 0xa8, 0xa3, 0x31, 0xff, 0x9c, 0x9b, 0xa2, 0x66,
	0xf4, 0xc2, 0xa6, 0xb2, 0xae, 0x82, 0x9c, 0xc2, 0xa0, 0x69, 0x2b, 0x04, 0x12, 0xa5, 0xd1, 0x1c,
	0x61, 0x23, 0xb0, 0xcc, 0xea, 0x84, 0xc0, 0x10, 0x57, 0xb2, 0x40, 0x06, 0x19, 0x9e, 0x93, 0xef,
	0x1e, 0x1c, 0xa8, 0x54, 0x9d, 0x4b, 0x51, 0x72, 0xdd, 0x58, 0xb6, 0x27, 0x10, 0x4a, 0xa5, 0x73,
	0xc3, 0xa5, 0xc0, 0x91, 0x07, 0xd9, 0x3e, 0x26, 0x87, 0xe0, 0x73, 0xea, 0x80, 0xfb, 0x9c, 0x92,
	0x23, 0x18, 0x99, 0xad, 0xc5, 0xd5, 0x31, 0x1e, 0x9a, 0xed, 0x25, 0xbd, 0x07, 0xee, 0x31, 0x04,
	0x35, 0xe3, 0x55, 0x6d, 0x10, 0xed, 0x30, 0x73, 0x11, 0x39, 0x05, 0x58, 0x5d, 0xcb, 0x62, 0xbd,
	0xac, 0xf3, 0xb6, 0x46, 0xba, 0x93, 0x6c, 0x82, 0xca, 0xfb, 0xbc, 0xad, 0x7b, 0xe0, 0xc7, 0x7f,
	0x02, 0x1f, 0xee, 0xc1, 0x27, 0x6b, 0x38, 0xfc, 0x9a, 0x73, 0xf3, 0x97, 0x2f, 0xd9, 0x2f, 0xe9,
	0xf7, 0x97, 0x7c, 0x0a, 0x43, 0x2e, 0x4a, 0x89, 0xcf, 0x41, 0xd4, 0x1d, 0x41, 0xd7, 0xd3, 0xda,
	0x91, 0x61, 0x41, 0x92, 0xc3, 0xe1, 0xaf, 0xfa, 0xbf, 0xd8, 0xf4, 0xa4, 0x6f, 0x13, 0xf9, 0x6d,
	0xc8, 0xce, 0xad, 0xe4, 0x13, 0xe0, 0x27, 0xcd, 0xe8, 0xd5, 0xf6, 0x8e, 0xb3, 0xd7, 0xe3, 0xbc,
	0xb3, 0xd3, 0xbf, 0xb3, 0x13, 0x7f, 0x18, 0xbc, 0x12, 0x4b, 0xc3, 0x74, 0xe3, 0x7c, 0x0e, 0xad,
	0x70, 0xc5, 0x74, 0x93, 0x7c, 0xf3, 0x20, 0x30, 0xdb, 0x8f, 0x92, 0x32, 0xfb, 0xfc, 0x9b, 0xfc,
	0x7a, 0xc3, 0x5c, 0xc3, 0x2e, 0x20, 0x0b, 0x08, 0x8a, 0x9a, 0x5f, 0xd3, 0x36, 0xf6, 0xa7, 0x83,
	0x59, 0x94, 0x3e, 0xc4, 0xdd, 0xba, 0x2b, 0xf3, 0x73, 0xcc, 0x5c, 0x08, 0xa3, 0x6f, 0x33, 0x57,
	0x76, 0xf2, 0x0e, 0xa2, 0x9e, 0x6c, 0x4d, 0x59, 0xb3, 0x5b, 0xd7, 0xd3, 0x1e, 0xc9, 0xd9, 0x6e,
	0x4e, 0xff, 0x9b, 0xec, 0x1a, 0xba, 0xa1, 0x6f, 0xfc, 0xd7, 0xde, 0x2a, 0x40, 0x58, 0xaf, 0x7e,
	0x06, 0x00, 0x00, 0xff, 0xff, 0x5c, 0xc3, 0xb6, 0x62, 0x47, 0x04, 0x00, 0x00,
}
