// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ofgp/ofgp-core/business/p2p/p2p.proto

package p2p

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import proto1 "github.com/ofgp/ofgp-core/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type P2PMsg struct {
	SendAddr             []byte   `protobuf:"bytes,1,opt,name=send_addr,json=sendAddr,proto3" json:"send_addr,omitempty"`
	ReceiveAddr          []byte   `protobuf:"bytes,2,opt,name=receive_addr,json=receiveAddr,proto3" json:"receive_addr,omitempty"`
	Chain                uint32   `protobuf:"varint,3,opt,name=chain,proto3" json:"chain,omitempty"`
	TokenId              uint32   `protobuf:"varint,4,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	FromToken            uint32   `protobuf:"varint,5,opt,name=from_token,json=fromToken,proto3" json:"from_token,omitempty"`
	Amount               uint64   `protobuf:"varint,6,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee                  uint64   `protobuf:"varint,7,opt,name=fee,proto3" json:"fee,omitempty"`
	ExpiredTime          uint32   `protobuf:"varint,8,opt,name=expired_time,json=expiredTime,proto3" json:"expired_time,omitempty"`
	RequireAddr          []byte   `protobuf:"bytes,9,opt,name=require_addr,json=requireAddr,proto3" json:"require_addr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PMsg) Reset()         { *m = P2PMsg{} }
func (m *P2PMsg) String() string { return proto.CompactTextString(m) }
func (*P2PMsg) ProtoMessage()    {}
func (*P2PMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_86a10fa743ff8601, []int{0}
}
func (m *P2PMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PMsg.Unmarshal(m, b)
}
func (m *P2PMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PMsg.Marshal(b, m, deterministic)
}
func (dst *P2PMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PMsg.Merge(dst, src)
}
func (m *P2PMsg) XXX_Size() int {
	return xxx_messageInfo_P2PMsg.Size(m)
}
func (m *P2PMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PMsg.DiscardUnknown(m)
}

var xxx_messageInfo_P2PMsg proto.InternalMessageInfo

func (m *P2PMsg) GetSendAddr() []byte {
	if m != nil {
		return m.SendAddr
	}
	return nil
}

func (m *P2PMsg) GetReceiveAddr() []byte {
	if m != nil {
		return m.ReceiveAddr
	}
	return nil
}

func (m *P2PMsg) GetChain() uint32 {
	if m != nil {
		return m.Chain
	}
	return 0
}

func (m *P2PMsg) GetTokenId() uint32 {
	if m != nil {
		return m.TokenId
	}
	return 0
}

func (m *P2PMsg) GetFromToken() uint32 {
	if m != nil {
		return m.FromToken
	}
	return 0
}

func (m *P2PMsg) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *P2PMsg) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

func (m *P2PMsg) GetExpiredTime() uint32 {
	if m != nil {
		return m.ExpiredTime
	}
	return 0
}

func (m *P2PMsg) GetRequireAddr() []byte {
	if m != nil {
		return m.RequireAddr
	}
	return nil
}

// 待匹配交易
type P2PInfo struct {
	Event                *proto1.WatchedEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Msg                  *P2PMsg              `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Time                 int64                `protobuf:"varint,3,opt,name=time,proto3" json:"time,omitempty"`
	Index                uint32               `protobuf:"varint,4,opt,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *P2PInfo) Reset()         { *m = P2PInfo{} }
func (m *P2PInfo) String() string { return proto.CompactTextString(m) }
func (*P2PInfo) ProtoMessage()    {}
func (*P2PInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_86a10fa743ff8601, []int{1}
}
func (m *P2PInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PInfo.Unmarshal(m, b)
}
func (m *P2PInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PInfo.Marshal(b, m, deterministic)
}
func (dst *P2PInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PInfo.Merge(dst, src)
}
func (m *P2PInfo) XXX_Size() int {
	return xxx_messageInfo_P2PInfo.Size(m)
}
func (m *P2PInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PInfo.DiscardUnknown(m)
}

var xxx_messageInfo_P2PInfo proto.InternalMessageInfo

func (m *P2PInfo) GetEvent() *proto1.WatchedEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *P2PInfo) GetMsg() *P2PMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *P2PInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *P2PInfo) GetIndex() uint32 {
	if m != nil {
		return m.Index
	}
	return 0
}

type P2PConfirmMsg struct {
	Opration             uint32   `protobuf:"varint,1,opt,name=opration,proto3" json:"opration,omitempty"`
	Id                   string   `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	TxId                 string   `protobuf:"bytes,3,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	Chain                uint32   `protobuf:"varint,4,opt,name=chain,proto3" json:"chain,omitempty"`
	Height               uint64   `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	BlockHash            string   `protobuf:"bytes,6,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	Amount               uint64   `protobuf:"varint,7,opt,name=amount,proto3" json:"amount,omitempty"`
	Fee                  uint64   `protobuf:"varint,8,opt,name=fee,proto3" json:"fee,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *P2PConfirmMsg) Reset()         { *m = P2PConfirmMsg{} }
func (m *P2PConfirmMsg) String() string { return proto.CompactTextString(m) }
func (*P2PConfirmMsg) ProtoMessage()    {}
func (*P2PConfirmMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_86a10fa743ff8601, []int{2}
}
func (m *P2PConfirmMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PConfirmMsg.Unmarshal(m, b)
}
func (m *P2PConfirmMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PConfirmMsg.Marshal(b, m, deterministic)
}
func (dst *P2PConfirmMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PConfirmMsg.Merge(dst, src)
}
func (m *P2PConfirmMsg) XXX_Size() int {
	return xxx_messageInfo_P2PConfirmMsg.Size(m)
}
func (m *P2PConfirmMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PConfirmMsg.DiscardUnknown(m)
}

var xxx_messageInfo_P2PConfirmMsg proto.InternalMessageInfo

func (m *P2PConfirmMsg) GetOpration() uint32 {
	if m != nil {
		return m.Opration
	}
	return 0
}

func (m *P2PConfirmMsg) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *P2PConfirmMsg) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *P2PConfirmMsg) GetChain() uint32 {
	if m != nil {
		return m.Chain
	}
	return 0
}

func (m *P2PConfirmMsg) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *P2PConfirmMsg) GetBlockHash() string {
	if m != nil {
		return m.BlockHash
	}
	return ""
}

func (m *P2PConfirmMsg) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *P2PConfirmMsg) GetFee() uint64 {
	if m != nil {
		return m.Fee
	}
	return 0
}

type WaitConfirmMsg struct {
	ScTxId               string          `protobuf:"bytes,1,opt,name=sc_tx_id,json=scTxId,proto3" json:"sc_tx_id,omitempty"`
	Opration             uint32          `protobuf:"varint,2,opt,name=opration,proto3" json:"opration,omitempty"`
	Chain                uint32          `protobuf:"varint,3,opt,name=chain,proto3" json:"chain,omitempty"`
	Info                 *P2PConfirmInfo `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	Time                 int64           `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *WaitConfirmMsg) Reset()         { *m = WaitConfirmMsg{} }
func (m *WaitConfirmMsg) String() string { return proto.CompactTextString(m) }
func (*WaitConfirmMsg) ProtoMessage()    {}
func (*WaitConfirmMsg) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_86a10fa743ff8601, []int{3}
}
func (m *WaitConfirmMsg) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaitConfirmMsg.Unmarshal(m, b)
}
func (m *WaitConfirmMsg) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaitConfirmMsg.Marshal(b, m, deterministic)
}
func (dst *WaitConfirmMsg) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaitConfirmMsg.Merge(dst, src)
}
func (m *WaitConfirmMsg) XXX_Size() int {
	return xxx_messageInfo_WaitConfirmMsg.Size(m)
}
func (m *WaitConfirmMsg) XXX_DiscardUnknown() {
	xxx_messageInfo_WaitConfirmMsg.DiscardUnknown(m)
}

var xxx_messageInfo_WaitConfirmMsg proto.InternalMessageInfo

func (m *WaitConfirmMsg) GetScTxId() string {
	if m != nil {
		return m.ScTxId
	}
	return ""
}

func (m *WaitConfirmMsg) GetOpration() uint32 {
	if m != nil {
		return m.Opration
	}
	return 0
}

func (m *WaitConfirmMsg) GetChain() uint32 {
	if m != nil {
		return m.Chain
	}
	return 0
}

func (m *WaitConfirmMsg) GetInfo() *P2PConfirmInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func (m *WaitConfirmMsg) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 被确认交易
type P2PConfirmInfo struct {
	Event                *proto1.WatchedEvent `protobuf:"bytes,1,opt,name=event,proto3" json:"event,omitempty"`
	Msg                  *P2PConfirmMsg       `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *P2PConfirmInfo) Reset()         { *m = P2PConfirmInfo{} }
func (m *P2PConfirmInfo) String() string { return proto.CompactTextString(m) }
func (*P2PConfirmInfo) ProtoMessage()    {}
func (*P2PConfirmInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_86a10fa743ff8601, []int{4}
}
func (m *P2PConfirmInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_P2PConfirmInfo.Unmarshal(m, b)
}
func (m *P2PConfirmInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_P2PConfirmInfo.Marshal(b, m, deterministic)
}
func (dst *P2PConfirmInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_P2PConfirmInfo.Merge(dst, src)
}
func (m *P2PConfirmInfo) XXX_Size() int {
	return xxx_messageInfo_P2PConfirmInfo.Size(m)
}
func (m *P2PConfirmInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_P2PConfirmInfo.DiscardUnknown(m)
}

var xxx_messageInfo_P2PConfirmInfo proto.InternalMessageInfo

func (m *P2PConfirmInfo) GetEvent() *proto1.WatchedEvent {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *P2PConfirmInfo) GetMsg() *P2PConfirmMsg {
	if m != nil {
		return m.Msg
	}
	return nil
}

type SendedInfo struct {
	TxId                 string   `protobuf:"bytes,1,opt,name=tx_id,json=txId,proto3" json:"tx_id,omitempty"`
	SignTerm             int64    `protobuf:"varint,2,opt,name=sign_term,json=signTerm,proto3" json:"sign_term,omitempty"`
	Chain                uint32   `protobuf:"varint,3,opt,name=chain,proto3" json:"chain,omitempty"`
	SignBeforeTxId       string   `protobuf:"bytes,4,opt,name=sign_before_tx_id,json=signBeforeTxId,proto3" json:"sign_before_tx_id,omitempty"`
	Time                 int64    `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SendedInfo) Reset()         { *m = SendedInfo{} }
func (m *SendedInfo) String() string { return proto.CompactTextString(m) }
func (*SendedInfo) ProtoMessage()    {}
func (*SendedInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_86a10fa743ff8601, []int{5}
}
func (m *SendedInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SendedInfo.Unmarshal(m, b)
}
func (m *SendedInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SendedInfo.Marshal(b, m, deterministic)
}
func (dst *SendedInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SendedInfo.Merge(dst, src)
}
func (m *SendedInfo) XXX_Size() int {
	return xxx_messageInfo_SendedInfo.Size(m)
}
func (m *SendedInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_SendedInfo.DiscardUnknown(m)
}

var xxx_messageInfo_SendedInfo proto.InternalMessageInfo

func (m *SendedInfo) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *SendedInfo) GetSignTerm() int64 {
	if m != nil {
		return m.SignTerm
	}
	return 0
}

func (m *SendedInfo) GetChain() uint32 {
	if m != nil {
		return m.Chain
	}
	return 0
}

func (m *SendedInfo) GetSignBeforeTxId() string {
	if m != nil {
		return m.SignBeforeTxId
	}
	return ""
}

func (m *SendedInfo) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// 创建待匹配交易索引
type TxNode struct {
	Value                string             `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Childs               map[string]*TxNode `protobuf:"bytes,2,rep,name=childs,proto3" json:"childs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *TxNode) Reset()         { *m = TxNode{} }
func (m *TxNode) String() string { return proto.CompactTextString(m) }
func (*TxNode) ProtoMessage()    {}
func (*TxNode) Descriptor() ([]byte, []int) {
	return fileDescriptor_p2p_86a10fa743ff8601, []int{6}
}
func (m *TxNode) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TxNode.Unmarshal(m, b)
}
func (m *TxNode) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TxNode.Marshal(b, m, deterministic)
}
func (dst *TxNode) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TxNode.Merge(dst, src)
}
func (m *TxNode) XXX_Size() int {
	return xxx_messageInfo_TxNode.Size(m)
}
func (m *TxNode) XXX_DiscardUnknown() {
	xxx_messageInfo_TxNode.DiscardUnknown(m)
}

var xxx_messageInfo_TxNode proto.InternalMessageInfo

func (m *TxNode) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func (m *TxNode) GetChilds() map[string]*TxNode {
	if m != nil {
		return m.Childs
	}
	return nil
}

func init() {
	proto.RegisterType((*P2PMsg)(nil), "p2p.p2pMsg")
	proto.RegisterType((*P2PInfo)(nil), "p2p.p2pInfo")
	proto.RegisterType((*P2PConfirmMsg)(nil), "p2p.p2pConfirmMsg")
	proto.RegisterType((*WaitConfirmMsg)(nil), "p2p.waitConfirmMsg")
	proto.RegisterType((*P2PConfirmInfo)(nil), "p2p.p2pConfirmInfo")
	proto.RegisterType((*SendedInfo)(nil), "p2p.sendedInfo")
	proto.RegisterType((*TxNode)(nil), "p2p.txNode")
	proto.RegisterMapType((map[string]*TxNode)(nil), "p2p.txNode.ChildsEntry")
}

func init() {
	proto.RegisterFile("github.com/ofgp/ofgp-core/business/p2p/p2p.proto", fileDescriptor_p2p_86a10fa743ff8601)
}

var fileDescriptor_p2p_86a10fa743ff8601 = []byte{
	// 643 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x53, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x63, 0xc7, 0x71, 0xc6, 0x6d, 0x04, 0x5b, 0x54, 0x4c, 0x51, 0xa5, 0x34, 0x42, 0x22,
	0x15, 0x22, 0x41, 0xe6, 0x82, 0xb8, 0x41, 0x55, 0x44, 0x0f, 0x70, 0xb0, 0x22, 0x71, 0xb4, 0x1c,
	0xef, 0x3a, 0x5e, 0xb5, 0xde, 0x5d, 0xd6, 0x9b, 0x92, 0x1e, 0xb8, 0x73, 0xe7, 0x80, 0xf8, 0x22,
	0x7e, 0x0b, 0xed, 0xd8, 0x4d, 0x4d, 0xd5, 0x1e, 0x38, 0x24, 0xf2, 0xbc, 0x99, 0x9d, 0x79, 0xf3,
	0xde, 0x2e, 0xbc, 0x5a, 0x71, 0x53, 0xae, 0x97, 0xb3, 0x5c, 0x56, 0x73, 0x59, 0xac, 0x14, 0xfe,
	0xbd, 0xcc, 0xa5, 0x66, 0xf3, 0xe5, 0xba, 0xe6, 0x82, 0xd5, 0xf5, 0x5c, 0xc5, 0xca, 0xfe, 0x66,
	0x4a, 0x4b, 0x23, 0x89, 0xab, 0x62, 0x75, 0xf0, 0xe2, 0xfe, 0x63, 0x58, 0x35, 0x5f, 0xea, 0xac,
	0x30, 0xcd, 0x89, 0xc9, 0x8f, 0x1e, 0xf8, 0x2a, 0x56, 0x9f, 0xea, 0x15, 0x79, 0x0a, 0xc3, 0x9a,
	0x09, 0x9a, 0x66, 0x94, 0xea, 0xc8, 0x19, 0x3b, 0xd3, 0x9d, 0x24, 0xb0, 0xc0, 0x3b, 0x4a, 0x35,
	0x39, 0x82, 0x1d, 0xcd, 0x72, 0xc6, 0x2f, 0x59, 0x93, 0xef, 0x61, 0x3e, 0x6c, 0x31, 0x2c, 0x79,
	0x04, 0xfd, 0xbc, 0xcc, 0xb8, 0x88, 0xdc, 0xb1, 0x33, 0xdd, 0x4d, 0x9a, 0x80, 0x3c, 0x81, 0xc0,
	0xc8, 0x73, 0x26, 0x52, 0x4e, 0x23, 0x0f, 0x13, 0x03, 0x8c, 0xcf, 0x28, 0x39, 0x04, 0x28, 0xb4,
	0xac, 0x52, 0x8c, 0xa3, 0x3e, 0x26, 0x87, 0x16, 0x59, 0x58, 0x80, 0xec, 0x83, 0x9f, 0x55, 0x72,
	0x2d, 0x4c, 0xe4, 0x8f, 0x9d, 0xa9, 0x97, 0xb4, 0x11, 0x79, 0x00, 0x6e, 0xc1, 0x58, 0x34, 0x40,
	0xd0, 0x7e, 0x5a, 0x72, 0x6c, 0xa3, 0xb8, 0x66, 0x34, 0x35, 0xbc, 0x62, 0x51, 0x80, 0xad, 0xc2,
	0x16, 0x5b, 0xf0, 0x8a, 0x35, 0xfc, 0xbf, 0xae, 0xb9, 0x6e, 0xf9, 0x0f, 0xaf, 0xf9, 0x23, 0x66,
	0xf9, 0x4f, 0xbe, 0xc3, 0x40, 0xc5, 0xea, 0x4c, 0x14, 0x92, 0x1c, 0x43, 0x9f, 0x5d, 0x32, 0x61,
	0x50, 0x86, 0x30, 0xde, 0x6b, 0xc4, 0x9a, 0x7d, 0xc9, 0x4c, 0x5e, 0x32, 0x7a, 0x6a, 0x53, 0x49,
	0x53, 0x41, 0x0e, 0xc1, 0xad, 0xea, 0x15, 0xea, 0x11, 0xc6, 0xe1, 0x0c, 0xbd, 0x40, 0x3d, 0x13,
	0x8b, 0x13, 0x02, 0x1e, 0x52, 0xb2, 0x9a, 0xb8, 0x09, 0x7e, 0x5b, 0xa1, 0xb8, 0xa0, 0x6c, 0xd3,
	0xea, 0xd1, 0x04, 0x93, 0x3f, 0x0e, 0xec, 0xaa, 0x58, 0x9d, 0x48, 0x51, 0x70, 0x5d, 0x59, 0x43,
	0x0e, 0x20, 0x90, 0x4a, 0x67, 0x86, 0x4b, 0x81, 0x44, 0x76, 0x93, 0x6d, 0x4c, 0x46, 0xd0, 0xe3,
	0x14, 0xa7, 0x0e, 0x93, 0x1e, 0xa7, 0x64, 0x0f, 0xfa, 0x66, 0x63, 0x35, 0x76, 0x11, 0xf2, 0xcc,
	0xe6, 0x8c, 0xde, 0x38, 0xe2, 0x75, 0x1d, 0xd9, 0x07, 0xbf, 0x64, 0x7c, 0x55, 0x1a, 0x94, 0xdc,
	0x4b, 0xda, 0xc8, 0xda, 0xb1, 0xbc, 0x90, 0xf9, 0x79, 0x5a, 0x66, 0x75, 0x89, 0x9a, 0x0f, 0x93,
	0x21, 0x22, 0x1f, 0xb3, 0xba, 0xec, 0xd8, 0x31, 0xb8, 0xcb, 0x8e, 0x60, 0x6b, 0xc7, 0xe4, 0xb7,
	0x03, 0xa3, 0x6f, 0x19, 0x37, 0x9d, 0x55, 0x22, 0x08, 0xea, 0x3c, 0x6d, 0x18, 0x3a, 0xd8, 0xd9,
	0xaf, 0xf3, 0x85, 0xe5, 0xd8, 0x5d, 0xb2, 0x77, 0x6b, 0xc9, 0xbb, 0x6f, 0xd4, 0x73, 0xf0, 0xb8,
	0x28, 0x24, 0x2e, 0x85, 0xde, 0x34, 0x92, 0xb7, 0xd3, 0xac, 0x7f, 0x09, 0x16, 0x6c, 0xb5, 0xef,
	0xdf, 0x68, 0x3f, 0xc9, 0x60, 0xf4, 0x6f, 0xed, 0xff, 0x78, 0xfd, 0xac, 0xeb, 0x35, 0xb9, 0x35,
	0xf8, 0xda, 0xf2, 0xc9, 0x4f, 0x07, 0xc0, 0xbe, 0x1b, 0x46, 0xb1, 0xff, 0xd6, 0x19, 0xa7, 0xe3,
	0x8c, 0x7d, 0x6b, 0x7c, 0x25, 0x52, 0xc3, 0x74, 0x85, 0xfd, 0xdc, 0x24, 0xb0, 0xc0, 0x82, 0xe9,
	0xea, 0x9e, 0xb5, 0x8f, 0xe1, 0x21, 0x1e, 0x59, 0xb2, 0x42, 0x6a, 0xd6, 0x6a, 0xe9, 0x61, 0xcf,
	0x91, 0x4d, 0xbc, 0x47, 0x1c, 0x35, 0xbd, 0x6b, 0xf1, 0x5f, 0x0e, 0xf8, 0x66, 0xf3, 0x59, 0x52,
	0xbc, 0x7f, 0x97, 0xd9, 0xc5, 0x9a, 0xb5, 0x8c, 0x9a, 0x80, 0xcc, 0xc1, 0xcf, 0x4b, 0x7e, 0x41,
	0xeb, 0xa8, 0x37, 0x76, 0xa7, 0x61, 0xfc, 0x18, 0xf7, 0x6b, 0x8e, 0xcc, 0x4e, 0x30, 0x73, 0x2a,
	0x8c, 0xbe, 0x4a, 0xda, 0xb2, 0x83, 0x0f, 0x10, 0x76, 0x60, 0x7b, 0x0f, 0xce, 0xd9, 0x55, 0xdb,
	0xd3, 0x7e, 0x92, 0xa3, 0xeb, 0x39, 0xdd, 0xc7, 0xd1, 0x34, 0x6c, 0x87, 0xbe, 0xed, 0xbd, 0x71,
	0x96, 0x3e, 0x0a, 0xfe, 0xfa, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xaa, 0x13, 0x16, 0xf9, 0xef,
	0x04, 0x00, 0x00,
}
