// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/ofgp/ofgp-core/business/mint/mint.proto

package mint

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MintRequire struct {
	ChainCode            uint32   `protobuf:"varint,1,opt,name=chain_code,json=chainCode,proto3" json:"chain_code,omitempty"`
	TokenCode            uint32   `protobuf:"varint,2,opt,name=token_code,json=tokenCode,proto3" json:"token_code,omitempty"`
	Receiver             []byte   `protobuf:"bytes,3,opt,name=receiver,proto3" json:"receiver,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MintRequire) Reset()         { *m = MintRequire{} }
func (m *MintRequire) String() string { return proto.CompactTextString(m) }
func (*MintRequire) ProtoMessage()    {}
func (*MintRequire) Descriptor() ([]byte, []int) {
	return fileDescriptor_mint_5535202a88bed367, []int{0}
}
func (m *MintRequire) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MintRequire.Unmarshal(m, b)
}
func (m *MintRequire) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MintRequire.Marshal(b, m, deterministic)
}
func (dst *MintRequire) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MintRequire.Merge(dst, src)
}
func (m *MintRequire) XXX_Size() int {
	return xxx_messageInfo_MintRequire.Size(m)
}
func (m *MintRequire) XXX_DiscardUnknown() {
	xxx_messageInfo_MintRequire.DiscardUnknown(m)
}

var xxx_messageInfo_MintRequire proto.InternalMessageInfo

func (m *MintRequire) GetChainCode() uint32 {
	if m != nil {
		return m.ChainCode
	}
	return 0
}

func (m *MintRequire) GetTokenCode() uint32 {
	if m != nil {
		return m.TokenCode
	}
	return 0
}

func (m *MintRequire) GetReceiver() []byte {
	if m != nil {
		return m.Receiver
	}
	return nil
}

func init() {
	proto.RegisterType((*MintRequire)(nil), "mint.mintRequire")
}

func init() {
	proto.RegisterFile("github.com/ofgp/ofgp-core/business/mint/mint.proto", fileDescriptor_mint_5535202a88bed367)
}

var fileDescriptor_mint_5535202a88bed367 = []byte{
	// 152 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x4a, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0x4f, 0x4b, 0x2f, 0x00, 0x13, 0xba, 0xc9, 0xf9,
	0x45, 0xa9, 0xfa, 0x49, 0xa5, 0xc5, 0x99, 0x79, 0xa9, 0xc5, 0xc5, 0xfa, 0xb9, 0x99, 0x79, 0x25,
	0x60, 0x42, 0xaf, 0xa0, 0x28, 0xbf, 0x24, 0x5f, 0x88, 0x05, 0xc4, 0x56, 0x4a, 0xe7, 0xe2, 0x06,
	0xd1, 0x41, 0xa9, 0x85, 0xa5, 0x99, 0x45, 0xa9, 0x42, 0xb2, 0x5c, 0x5c, 0xc9, 0x19, 0x89, 0x99,
	0x79, 0xf1, 0xc9, 0xf9, 0x29, 0xa9, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xbc, 0x41, 0x9c, 0x60, 0x11,
	0xe7, 0xfc, 0x14, 0xb0, 0x74, 0x49, 0x7e, 0x76, 0x2a, 0x54, 0x9a, 0x09, 0x22, 0x0d, 0x16, 0x01,
	0x4b, 0x4b, 0x71, 0x71, 0x14, 0xa5, 0x26, 0xa7, 0x66, 0x96, 0xa5, 0x16, 0x49, 0x30, 0x2b, 0x30,
	0x6a, 0xf0, 0x04, 0xc1, 0xf9, 0x49, 0x6c, 0x60, 0x5b, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xff, 0xb4, 0xd2, 0x8f, 0xab, 0x00, 0x00, 0x00,
}
